version: "3.9"

x-backend-environment: &backend-environment
  DJANGO_SETTINGS_MODULE: settings.settings.prod
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0

x-backend-base: &backend-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/mm
    - ./logs:/mm/logs/
    - ./scripts:/mm/scripts/
    - ./src/static:/mm/src/static/
    - ./src/media:/mm/src/media/

x-backend: &backend
  image: app:django
  <<: *backend-base
  environment:
    <<: *backend-environment

services:

  # Redis
  redis:
    image: redis:alpine
    container_name: mm_redis
    ports:
      - 6380:6379

  # Database Postgres
  db:
    image: postgres:15.4
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      # Остальные параметры конфигурации Postgres

  # Django WSGI App
  wsgi-server:
    <<: *backend
    ports:
      - 8000:8000
    links:
      - db
      - redis
    container_name: mm_wsgi
    command: sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-wsgi-web.sh"
    depends_on:
      db:
        condition: service_healthy

  # Celery
  celery-worker-beat:
    restart: always
    <<: *backend
    command: sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-worker.sh"
    volumes:
      - .:/mm
    container_name: mm_celery
    links:
      - redis
    depends_on:
      - db
      - redis
      - wsgi-server

  # Flower
  flower:
    <<: *backend
    command: sh -c "./scripts/wait-for-it.sh db:5432 -- sh ./scripts/entrypoint-flower.sh"
    volumes:
      - .:/mm
    ports:
      - 5555:5555
    links:
      - redis
      - celery-worker-beat
    container_name: mm_flower

  # Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    volumes:
      - ./src/static:/mm/src/static/
     
