# Generated by Django 5.0.6 on 2024-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMAPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(max_length=255)),
                ("queries_per_sec", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProxyServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(max_length=255)),
                ("queries_per_sec", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMTPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("port", models.IntegerField()),
                ("password", models.CharField(max_length=255)),
                ("queries_per_sec", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
