# Generated by Django 5.0.6 on 2024-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_servers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("template", models.TextField(blank=True, null=True)),
                ("message", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
