# Generated by Django 5.0.6 on 2024-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_servers', '0002_messagetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imapserver',
            name='queries_per_sec',
        ),
        migrations.RemoveField(
            model_name='proxyserver',
            name='queries_per_sec',
        ),
        migrations.RemoveField(
            model_name='smtpserver',
            name='queries_per_sec',
        ),
        migrations.AddField(
            model_name='imapserver',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imapserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imapserver',
            name='username',
            field=models.EmailField(default='default_imap@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='username',
            field=models.EmailField(default='default_proxy@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='username',
            field=models.EmailField(default='default_smtp@example.com', max_length=254),
        ),
    ]
