# Generated by Django 5.0.6 on 2024-07-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changelog",
            name="data_changes",
        ),
        migrations.AddField(
            model_name="changelog",
            name="data",
            field=models.JSONField(default=dict, verbose_name="Modifiable model data"),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
