# Nginx configuration for Django app

upstream django {
    server wsgi-server:8000;
}

server {
    listen 80;
    server_name your_domain.com; # Укажите доменное имя вашего приложения

    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /static/ {
        alias /mm/src/static/;
    }

    location /media/ {
        alias /mm/src/media/;
    }

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
